#ifndef HELTEC_WIFI_LORA_V3_H
#define HELTEC_WIFI_LORA_V3_H

#define PIN_LORA_NSS 8
#define PIN_LORA_SCK 9
#define PIN_LORA_MOSI 10
#define PIN_LORA_MISO 11
#define PIN_LORA_RST 12
#define PIN_LORA_BUSY 13
#define PIN_LORA_DIO1 14

#define LORA_FREQUENCY_MHZ 915
#define LORA_BANDWIDTH_KHZ 125
#define LORA_SPREADING_FACTOR 7
#define LORA_CODING_RATE_DENOMINATOR 5
#define LORA_SYNCWORD 0x12
#define LORA_POWER_DBM 10
#define LORA_PREAMBLE_LENGTH 8

#endif // HELTEC_WIFI_LORA_V3_H